In [14]:
import tensorflow as tf
import numpy


In [4]:
hello = tf.constant("Hello, TensorFlow!")

#seart a TF session
sess = tf.Session()

# run the operation and get result
print(sess.run(hello))

AttributeError: module 'tensorflow' has no attribute 'Session'

#### 위 방법은 tensorflow 1.X.X 버전 방법이라서 오류
#### 2.x.x 버전은 Session 정의하고 run해주는 과정이 생략됨

In [6]:
hello = tf.constant("Hello, TensorFlow!")
tf.print(hello)

Hello, TensorFlow!


In [7]:
node1 = tf.constant(3.0, tf.float32) # type 지정
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2) # node3 = node1 + node2 로 해도됨

In [8]:
print("node1 : ", node1, "node2 : ", node2)
print("node3 : ", node3)

node1 :  tf.Tensor(3.0, shape=(), dtype=float32) node2 :  tf.Tensor(4.0, shape=(), dtype=float32)
node3 :  tf.Tensor(7.0, shape=(), dtype=float32)


In [10]:
tf.print([node1, node2])
tf.print(node3)

[3, 4]
7


In [13]:
# tensorflow 1.x.x version -> 오류
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a+b

tf.print(adder_node, feed_dict={a:3, b:4.5})

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [15]:
# tensorflow 2.x.x version
@tf.function
def adder(a, b):
    return a+b

A=tf.constant(1)
B=tf.constant(2)
print(adder(A,B))

C=tf.constant([1,2])
D=tf.constant([3,4])
print(adder(C,D))

E=tf.constant([[1,2,3],[4,5,6]])
F=tf.constant([[2,3,4],[5,6,7]])
print(adder(E,F))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)


### 2.x.x version에서는 Session 과 placeholder 사용 X
### @tf.function을 통해 함수를 정의해서 사용