# Lab 4 Multi-variable linear regression

In [23]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [24]:
tf.set_random_seed(777)

<img src="score.jpg" width="200">

In [25]:
# 5명의 3번의 시험 점수
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]

In [26]:
# 5명의 기말시험 예측한 점수
y_data = [152.,185.,180.,196.,142.]

### placeholders for a tensor that will be fed

In [27]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [28]:
# 3번 시험이니 w도 3개 필요
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [29]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

### cost/loss function

In [30]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

### Minimize. Need a very small learning rate for this data set

In [31]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [32]:
# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [33]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step%10 == 0:
        print(step, "Cost : ", cost_val, "\nPrediction: \n", hy_val)

0 Cost :  24.329584 
Prediction: 
 [156.18037 182.38869 182.07524 202.24023 134.6443 ]
10 Cost :  23.504845 
Prediction: 
 [155.41048 181.49327 181.17747 201.26317 133.96829]
20 Cost :  23.407307 
Prediction: 
 [155.39246 181.50145 181.17014 201.2557  133.9815 ]
30 Cost :  23.31027 
Prediction: 
 [155.37672 181.5123  181.1654  201.25113 133.99672]
40 Cost :  23.213665 
Prediction: 
 [155.36107 181.52318 181.16078 201.24663 134.01196]
50 Cost :  23.117712 
Prediction: 
 [155.34544 181.53395 181.15611 201.2421  134.02711]
60 Cost :  23.022175 
Prediction: 
 [155.3299  181.54478 181.15152 201.23764 134.04228]
70 Cost :  22.927204 
Prediction: 
 [155.31433 181.55551 181.14688 201.23312 134.05734]
80 Cost :  22.832632 
Prediction: 
 [155.2989  181.5663  181.14232 201.22868 134.07245]
90 Cost :  22.73863 
Prediction: 
 [155.28342 181.57695 181.13773 201.22417 134.08743]
100 Cost :  22.645128 
Prediction: 
 [155.26802 181.58763 181.13316 201.21973 134.10242]
110 Cost :  22.552149 
Prediction:

1090 Cost :  15.442247 
Prediction: 
 [153.93854 182.51045 180.74031 200.82285 135.40852]
1100 Cost :  15.386836 
Prediction: 
 [153.92693 182.51854 180.7369  200.81926 135.42009]
1110 Cost :  15.331675 
Prediction: 
 [153.9153  182.5266  180.73346 200.81566 135.43161]
1120 Cost :  15.276796 
Prediction: 
 [153.90375 182.53464 180.73006 200.81209 135.44313]
1130 Cost :  15.222189 
Prediction: 
 [153.89223 182.5427  180.7267  200.80853 135.45462]
1140 Cost :  15.167943 
Prediction: 
 [153.8807  182.55066 180.7233  200.80495 135.46603]
1150 Cost :  15.113861 
Prediction: 
 [153.86926 182.55865 180.71996 200.80139 135.47748]
1160 Cost :  15.060176 
Prediction: 
 [153.8578  182.56657 180.71657 200.79782 135.48883]
1170 Cost :  15.006666 
Prediction: 
 [153.84639 182.57452 180.71323 200.79428 135.5002 ]
1180 Cost :  14.953464 
Prediction: 
 [153.83505 182.58244 180.7099  200.79074 135.51154]
1190 Cost :  14.900572 
Prediction: 
 [153.82368 182.59032 180.70654 200.7872  135.52281]
1200 Cost 

### 기말 예측 점수 결과

|원래|tensorflow가 구한것|
|:---:|:---:|
|152||
|185||
|180||
|196||
|142||

### 여기에서는 variable 3개 (x1,x2,x3)에 5명 data 였음
### 만약에 varaible 도 더 많고 data가 엄청엄청 많아지면 이렇게 직접 리스트로 적는것이 매우매우 비효율적
### => matrix 사용
### ML lab 4-2.ipynb 참고