# Lab 4 Multi-variable linear regression

In [26]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)

In [27]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

In [28]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [29]:
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

### collect batches of csv in

In [30]:
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

- batch_size=10 : 한번에 10개씩 가져와서 실행

### placeholders for a tensor that will be always fed.

In [31]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

### Hypothesis

In [32]:
hypothesis = tf.matmul(X, W) + b

### Simplified cost/loss function

In [34]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

### Minimize


In [35]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [36]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

### Start populating the filename queue.

In [39]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [40]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  89273.25 
Prediction:
 [[-133.5243 ]
 [-164.79396]
 [-160.21033]
 [-174.73906]
 [-126.36729]
 [ -93.72274]
 [-129.70605]
 [ -94.58198]
 [-155.14684]
 [-144.42427]]
10 Cost:  17.85369 
Prediction:
 [[154.26001]
 [181.17358]
 [180.63579]
 [196.48616]
 [137.49376]
 [100.84798]
 [148.174  ]
 [111.42605]
 [168.22433]
 [155.14264]]
20 Cost:  11.912735 
Prediction:
 [[156.1897  ]
 [183.51485 ]
 [182.93082 ]
 [198.99222 ]
 [139.27937 ]
 [102.17717 ]
 [150.05351 ]
 [112.823845]
 [170.42555 ]
 [157.19806 ]]
30 Cost:  11.821232 
Prediction:
 [[156.19043 ]
 [183.53722 ]
 [182.94124 ]
 [199.01007 ]
 [139.2964  ]
 [102.202255]
 [150.0705  ]
 [112.840866]
 [170.45937 ]
 [157.24564 ]]
40 Cost:  11.742627 
Prediction:
 [[156.17819]
 [183.54388]
 [182.93628]
 [199.01111]
 [139.30148]
 [102.21845]
 [150.07487]
 [112.84852]
 [170.47845]
 [157.27951]]
50 Cost:  11.664871 
Prediction:
 [[156.16591]
 [183.55043]
 [182.93121]
 [199.01204]
 [139.30644]
 [102.23452]
 [150.07915]
 [112.85609]
 [170.4973

580 Cost:  8.480066 
Prediction:
 [[155.59018 ]
 [183.85728 ]
 [182.69412 ]
 [199.05597 ]
 [139.53926 ]
 [102.988716]
 [150.28079 ]
 [113.212036]
 [171.3848  ]
 [158.89206 ]]
590 Cost:  8.434798 
Prediction:
 [[155.58058]
 [183.86237]
 [182.69017]
 [199.05669]
 [139.5431 ]
 [103.00126]
 [150.28415]
 [113.21798]
 [171.39955]
 [158.9183 ]]
600 Cost:  8.389997 
Prediction:
 [[155.57108]
 [183.86745]
 [182.68626]
 [199.05745]
 [139.54697]
 [103.01375]
 [150.28752]
 [113.22389]
 [171.41426]
 [158.94447]]
610 Cost:  8.3456335 
Prediction:
 [[155.56158 ]
 [183.8725  ]
 [182.68234 ]
 [199.05815 ]
 [139.55078 ]
 [103.02616 ]
 [150.29083 ]
 [113.229774]
 [171.42886 ]
 [158.97049 ]]
620 Cost:  8.301732 
Prediction:
 [[155.55214 ]
 [183.87752 ]
 [182.67845 ]
 [199.05888 ]
 [139.5546  ]
 [103.038536]
 [150.29416 ]
 [113.235634]
 [171.44344 ]
 [158.99638 ]]
630 Cost:  8.258265 
Prediction:
 [[155.54274]
 [183.88254]
 [182.67459]
 [199.05962]
 [139.5584 ]
 [103.05084]
 [150.29745]
 [113.24147]
 [171.

1190 Cost:  6.4176636 
Prediction:
 [[155.07976]
 [184.12883]
 [182.48369]
 [199.09525]
 [139.74463]
 [103.65731]
 [150.46071]
 [113.52979]
 [172.17168]
 [160.29312]]
1200 Cost:  6.393565 
Prediction:
 [[155.07251]
 [184.13269]
 [182.48071]
 [199.0958 ]
 [139.74753]
 [103.66679]
 [150.46326]
 [113.53432]
 [172.18283]
 [160.31299]]
1210 Cost:  6.369766 
Prediction:
 [[155.06532 ]
 [184.13649 ]
 [182.47774 ]
 [199.09634 ]
 [139.75041 ]
 [103.676216]
 [150.46582 ]
 [113.53881 ]
 [172.19392 ]
 [160.33275 ]]
1220 Cost:  6.3461533 
Prediction:
 [[155.05815]
 [184.14032]
 [182.47476]
 [199.0969 ]
 [139.7533 ]
 [103.6856 ]
 [150.46835]
 [113.5433 ]
 [172.20497]
 [160.35245]]
1230 Cost:  6.32285 
Prediction:
 [[155.05101 ]
 [184.14412 ]
 [182.47182 ]
 [199.09746 ]
 [139.75615 ]
 [103.694954]
 [150.47087 ]
 [113.54777 ]
 [172.21596 ]
 [160.37202 ]]
1240 Cost:  6.299759 
Prediction:
 [[155.0439 ]
 [184.14787]
 [182.46889]
 [199.09799]
 [139.75899]
 [103.70425]
 [150.47339]
 [113.5522 ]
 [172.2269

1800 Cost:  5.334646 
Prediction:
 [[154.69412]
 [184.33359]
 [182.3245 ]
 [199.12521]
 [139.89883]
 [104.16241]
 [150.59772]
 [113.77186]
 [172.76627]
 [161.35283]]
1810 Cost:  5.3222322 
Prediction:
 [[154.68864 ]
 [184.33647 ]
 [182.32222 ]
 [199.12564 ]
 [139.901   ]
 [104.169556]
 [150.59966 ]
 [113.77531 ]
 [172.77469 ]
 [161.36784 ]]
1820 Cost:  5.3099566 
Prediction:
 [[154.6832 ]
 [184.33937]
 [182.31998]
 [199.12605]
 [139.90317]
 [104.17668]
 [150.6016 ]
 [113.77873]
 [172.78308]
 [161.3828 ]]
1830 Cost:  5.2978315 
Prediction:
 [[154.6778 ]
 [184.34224]
 [182.31773]
 [199.12648]
 [139.90533]
 [104.18377]
 [150.60353]
 [113.78214]
 [172.79143]
 [161.39769]]
1840 Cost:  5.2858353 
Prediction:
 [[154.6724  ]
 [184.3451  ]
 [182.3155  ]
 [199.12689 ]
 [139.90747 ]
 [104.190834]
 [150.60545 ]
 [113.785545]
 [172.79974 ]
 [161.4125  ]]
1850 Cost:  5.274 
Prediction:
 [[154.66704]
 [184.34795]
 [182.3133 ]
 [199.12733]
 [139.90962]
 [104.19786]
 [150.60738]
 [113.78893]
 [172.808 

In [41]:
coord.request_stop()
coord.join(threads)

### Ask my score

In [42]:
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[181.26826]]
Other scores will be  [[174.64012]
 [179.69069]]
