# Lab 7 Learning rate and Evaluation

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np
tf.set_random_seed(777)

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

### Evaluation our model using this test dataset

In [4]:
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

### tf.nn.softmax computes softmax activations

In [5]:
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

### Cross entropy cost/loss

In [6]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

### Try to change learning_rate to small numbers

In [7]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

### Correct prediction Test model

In [8]:
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

### Launch graph

In [9]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.73203 [[ 0.7288166   0.7153621  -1.1801533 ]
 [-0.57753736 -0.12988332  1.6072978 ]
 [ 0.48373488 -0.51433605 -2.02127   ]]
1 3.3179948 [[ 0.6621908   0.7479632  -1.1461285 ]
 [-0.8194891   0.03000021  1.689366  ]
 [ 0.23214608 -0.33772916 -1.9462881 ]]
2 2.0218027 [[ 0.6434202   0.74127686 -1.1206716 ]
 [-0.81161296 -0.00900118  1.7204912 ]
 [ 0.2086665  -0.3507957  -1.909742  ]]
3 1.9710884 [[ 0.6235321   0.7400824  -1.099589  ]
 [-0.8096771  -0.01636279  1.725917  ]
 [ 0.17870614 -0.3366575  -1.8939198 ]]
4 1.9446772 [[ 0.60733104  0.7366499  -1.0799555 ]
 [-0.7900784  -0.03363194  1.7235874 ]
 [ 0.16691467 -0.3340635  -1.8847224 ]]
5 1.9235672 [[ 0.59031737  0.7351024  -1.0613943 ]
 [-0.7749677  -0.0404885   1.7153332 ]
 [ 0.15076597 -0.322094   -1.8805432 ]]
6 1.9035923 [[ 0.57437915  0.7326286  -1.0429822 ]
 [-0.75527775 -0.05152005  1.7066748 ]
 [ 0.13977793 -0.31497929 -1.8766699 ]]
7 1.8840802 [[ 0.5581266   0.7307179  -1.024819  ]
 [-0.73775685 -0.05928206  1.696916  ]
 [

119 0.86618555 [[-0.6675163   0.40881956  0.5227223 ]
 [ 0.18875834  0.01563374  0.69548565]
 [-0.34835327 -0.32100537 -1.3825121 ]]
120 0.8621567 [[-0.67484635  0.40643027  0.5324416 ]
 [ 0.19237772  0.01887337  0.68862665]
 [-0.34947637 -0.32348    -1.3789144 ]]
121 0.8581826 [[-0.6821365   0.40406197  0.5421    ]
 [ 0.19595897  0.02209275  0.681826  ]
 [-0.35057047 -0.32593453 -1.3753657 ]]
122 0.8542627 [[-0.689387    0.4017147   0.55169785]
 [ 0.1995024   0.02529118  0.6750841 ]
 [-0.3516356  -0.32836837 -1.3718668 ]]
123 0.8503968 [[-0.6965984   0.39938858  0.56123537]
 [ 0.20300817  0.02846803  0.6684015 ]
 [-0.3526718  -0.33078092 -1.3684181 ]]
124 0.84658426 [[-0.70377105  0.3970836   0.570713  ]
 [ 0.20647658  0.03162272  0.6617784 ]
 [-0.35367903 -0.33317164 -1.3650202 ]]
125 0.84282446 [[-0.71090525  0.39479986  0.58013093]
 [ 0.20990776  0.03475465  0.65521526]
 [-0.35465744 -0.33553997 -1.3616735 ]]
126 0.8391171 [[-0.7180014   0.39253736  0.5894896 ]
 [ 0.21330196  0.037